"""initial schema

Revision ID: 282043a24b96
Revises:
Create Date: 2026-09-28 17:32:32.288181

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "282043a24b96"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matches",
        sa.Column("match_id", sa.String(length=32), nullable=False),
        sa.Column("platform", sa.String(length=8), nullable=False),
        sa.Column("queue_id", sa.Integer(), nullable=True),
        sa.Column("game_mode", sa.String(length=16), nullable=True),
        sa.Column("game_start_ms", sa.Integer(), nullable=True),
        sa.Column("game_end_ms", sa.Integer(), nullable=True),
        sa.Column("duration_s", sa.Integer(), nullable=True),
        sa.Column("is_arena", sa.Boolean(), nullable=False),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column("fetched_at_ms", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("match_id"),
    )
    op.create_table(
        "members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("puuid", sa.String(length=78), nullable=False),
        sa.Column("game_name", sa.String(length=64), nullable=False),
        sa.Column("tag_line", sa.String(length=16), nullable=False),
        sa.Column("platform", sa.String(length=8), nullable=False),
        sa.Column("created_at_ms", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_polled_at_ms", sa.Integer(), nullable=True),
        sa.Column("backfill_from_ms", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("puuid"),
    )
    op.create_table(
        "member_games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.String(length=32), nullable=False),
        sa.Column("champion_name", sa.String(length=32), nullable=False),
        sa.Column("champion_id", sa.Integer(), nullable=True),
        sa.Column("placement", sa.Integer(), nullable=True),
        sa.Column("subteam_id", sa.Integer(), nullable=True),
        sa.Column("augments", sa.JSON(), nullable=False),
        sa.Column("damage_to_champions", sa.Integer(), nullable=True),
        sa.Column("physical_damage_to_champions", sa.Integer(), nullable=True),
        sa.Column("magic_damage_to_champions", sa.Integer(), nullable=True),
        sa.Column("true_damage_to_champions", sa.Integer(), nullable=True),
        sa.Column("largest_crit", sa.Integer(), nullable=True),
        sa.Column("damage_taken", sa.Integer(), nullable=True),
        sa.Column("damage_mitigated", sa.Integer(), nullable=True),
        sa.Column("total_heal", sa.Integer(), nullable=True),
        sa.Column("heals_on_teammates", sa.Integer(), nullable=True),
        sa.Column("shields_on_teammates", sa.Integer(), nullable=True),
        sa.Column("cc_time", sa.Integer(), nullable=True),
        sa.Column("largest_multikill", sa.Integer(), nullable=True),
        sa.Column("penta_kills", sa.Integer(), nullable=True),
        sa.Column("gold_earned", sa.Integer(), nullable=True),
        sa.Column("damage_per_minute", sa.Double(), nullable=True),
        sa.Column("final_ap", sa.Double(), nullable=True),
        sa.Column("peak_ap", sa.Double(), nullable=True),
        sa.Column("final_ad", sa.Double(), nullable=True),
        sa.Column("peak_ad", sa.Double(), nullable=True),
        sa.Column("final_health_max", sa.Double(), nullable=True),
        sa.Column("peak_health_max", sa.Double(), nullable=True),
        sa.Column("final_armor", sa.Double(), nullable=True),
        sa.Column("final_mr", sa.Double(), nullable=True),
        sa.Column("final_attack_speed", sa.Double(), nullable=True),
        sa.Column("peak_attack_speed", sa.Double(), nullable=True),
        sa.Column("game_end_ms", sa.Integer(), nullable=True),
        sa.Column("duration_s", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.match_id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_id", "member_id", name="uq_member_games_match_member"),
    )
    op.create_index("ix_member_games_game_end_ms", "member_games", ["game_end_ms"], unique=False)
    op.create_index(
        "ix_member_games_member_id_game_end_ms",
        "member_games",
        ["member_id", "game_end_ms"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_member_games_member_id_game_end_ms", table_name="member_games")
    op.drop_index("ix_member_games_game_end_ms", table_name="member_games")
    op.drop_table("member_games")
    op.drop_table("members")
    op.drop_table("matches")
    # ### end Alembic commands ###
